'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace BIMSICWS
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://bimsic.net/", ConfigurationName:="BIMSICWS.wsSistemaIntegradoWebBIMSICSoap")>  _
    Public Interface wsSistemaIntegradoWebBIMSICSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://bimsic.net/HelloWorld", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function HelloWorld() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://bimsic.net/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorldAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://bimsic.net/ConsultaRUC", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ConsultaRUC(ByVal RUC As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://bimsic.net/ConsultaRUC", ReplyAction:="*")>  _
        Function ConsultaRUCAsync(ByVal RUC As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://bimsic.net/ConsultaValidaEmpresa", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ConsultaValidaEmpresa(ByVal RUC As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://bimsic.net/ConsultaValidaEmpresa", ReplyAction:="*")>  _
        Function ConsultaValidaEmpresaAsync(ByVal RUC As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://bimsic.net/InsertaConsultaFE", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function InsertaConsultaFE(ByVal dFechaEmisionConsultaFE As Date, ByVal cIdTipoDocumentoConsultaFE As String, ByVal vIdNumeroSerieDocumentoConsultaFE As String, ByVal vIdNumeroCorrelativoConsultaFE As String, ByVal cIdTipoDocumentoClienteConsultaFE As String, ByVal vNumeroDocumentoClienteConsultaFE As String, ByVal nTotalPrecioVentaConsultaFE As Decimal, ByVal vRucEmpresaConsultaFE As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://bimsic.net/InsertaConsultaFE", ReplyAction:="*")>  _
        Function InsertaConsultaFEAsync(ByVal dFechaEmisionConsultaFE As Date, ByVal cIdTipoDocumentoConsultaFE As String, ByVal vIdNumeroSerieDocumentoConsultaFE As String, ByVal vIdNumeroCorrelativoConsultaFE As String, ByVal cIdTipoDocumentoClienteConsultaFE As String, ByVal vNumeroDocumentoClienteConsultaFE As String, ByVal nTotalPrecioVentaConsultaFE As Decimal, ByVal vRucEmpresaConsultaFE As String) As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface wsSistemaIntegradoWebBIMSICSoapChannel
        Inherits BIMSICWS.wsSistemaIntegradoWebBIMSICSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class wsSistemaIntegradoWebBIMSICSoapClient
        Inherits System.ServiceModel.ClientBase(Of BIMSICWS.wsSistemaIntegradoWebBIMSICSoap)
        Implements BIMSICWS.wsSistemaIntegradoWebBIMSICSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function HelloWorld() As String Implements BIMSICWS.wsSistemaIntegradoWebBIMSICSoap.HelloWorld
            Return MyBase.Channel.HelloWorld
        End Function
        
        Public Function HelloWorldAsync() As System.Threading.Tasks.Task(Of String) Implements BIMSICWS.wsSistemaIntegradoWebBIMSICSoap.HelloWorldAsync
            Return MyBase.Channel.HelloWorldAsync
        End Function
        
        Public Function ConsultaRUC(ByVal RUC As String) As System.Data.DataSet Implements BIMSICWS.wsSistemaIntegradoWebBIMSICSoap.ConsultaRUC
            Return MyBase.Channel.ConsultaRUC(RUC)
        End Function
        
        Public Function ConsultaRUCAsync(ByVal RUC As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements BIMSICWS.wsSistemaIntegradoWebBIMSICSoap.ConsultaRUCAsync
            Return MyBase.Channel.ConsultaRUCAsync(RUC)
        End Function
        
        Public Function ConsultaValidaEmpresa(ByVal RUC As String) As System.Data.DataSet Implements BIMSICWS.wsSistemaIntegradoWebBIMSICSoap.ConsultaValidaEmpresa
            Return MyBase.Channel.ConsultaValidaEmpresa(RUC)
        End Function
        
        Public Function ConsultaValidaEmpresaAsync(ByVal RUC As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements BIMSICWS.wsSistemaIntegradoWebBIMSICSoap.ConsultaValidaEmpresaAsync
            Return MyBase.Channel.ConsultaValidaEmpresaAsync(RUC)
        End Function
        
        Public Function InsertaConsultaFE(ByVal dFechaEmisionConsultaFE As Date, ByVal cIdTipoDocumentoConsultaFE As String, ByVal vIdNumeroSerieDocumentoConsultaFE As String, ByVal vIdNumeroCorrelativoConsultaFE As String, ByVal cIdTipoDocumentoClienteConsultaFE As String, ByVal vNumeroDocumentoClienteConsultaFE As String, ByVal nTotalPrecioVentaConsultaFE As Decimal, ByVal vRucEmpresaConsultaFE As String) As Boolean Implements BIMSICWS.wsSistemaIntegradoWebBIMSICSoap.InsertaConsultaFE
            Return MyBase.Channel.InsertaConsultaFE(dFechaEmisionConsultaFE, cIdTipoDocumentoConsultaFE, vIdNumeroSerieDocumentoConsultaFE, vIdNumeroCorrelativoConsultaFE, cIdTipoDocumentoClienteConsultaFE, vNumeroDocumentoClienteConsultaFE, nTotalPrecioVentaConsultaFE, vRucEmpresaConsultaFE)
        End Function
        
        Public Function InsertaConsultaFEAsync(ByVal dFechaEmisionConsultaFE As Date, ByVal cIdTipoDocumentoConsultaFE As String, ByVal vIdNumeroSerieDocumentoConsultaFE As String, ByVal vIdNumeroCorrelativoConsultaFE As String, ByVal cIdTipoDocumentoClienteConsultaFE As String, ByVal vNumeroDocumentoClienteConsultaFE As String, ByVal nTotalPrecioVentaConsultaFE As Decimal, ByVal vRucEmpresaConsultaFE As String) As System.Threading.Tasks.Task(Of Boolean) Implements BIMSICWS.wsSistemaIntegradoWebBIMSICSoap.InsertaConsultaFEAsync
            Return MyBase.Channel.InsertaConsultaFEAsync(dFechaEmisionConsultaFE, cIdTipoDocumentoConsultaFE, vIdNumeroSerieDocumentoConsultaFE, vIdNumeroCorrelativoConsultaFE, cIdTipoDocumentoClienteConsultaFE, vNumeroDocumentoClienteConsultaFE, nTotalPrecioVentaConsultaFE, vRucEmpresaConsultaFE)
        End Function
    End Class
End Namespace
